# Generated by Django 3.0.3 on 2020-03-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_auto_20200307_1635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehouse',
            options={'verbose_name': 'Almacen', 'verbose_name_plural': 'Almacen'},
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
