# Generated by Django 3.0.3 on 2020-03-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0008_auto_20200307_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='quantity',
            field=models.FloatField(default=0, verbose_name='Cantidad'),
        ),
    ]
