# Generated by Django 3.0.3 on 2020-03-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0009_auto_20200307_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Cantidad'),
        ),
    ]
