# Generated by Django 3.0.3 on 2020-03-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0013_auto_20200309_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Producto'),
        ),
    ]
